### ISSUE TITLE
kinetics models

### ISSUE THREAD

**Issue by slighting666** [mnmjh1215/CSN-PyTorch#1]
I'm sorry to interrupt, but can I get some information about the ip-csn and ir-csn network pre-trained on kinetic? Do you have this model?

**Comment by mnmjh1215** [comment]
Hi, thanks for your interest.
Unfortunately, I also do not have pretrained model. I do not have enough computing power to pretrain 3d convolutional model on such big dataset.

**Comment by slighting666** [comment]
I have some questions.can you help me？&nbsp;
my qq 1149745774



---Original---

**Comment by mnmjh1215** [comment]
Sure, I can help you, even though I do not have many experience on video classification task.
If you have any question, comment on this thread or email me.
